#!/usr/bin/env bash
#Bash script that displays messages when read some signals

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'rm /var/run/myscript.pid; exit' SIGQUIT
done
