#!/usr/bin/env bash
# groups visitors by IP and HTTP status code.
#  displays this data in list format.
#  Ordered from the greatest to the lowest number of occurrences.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
